using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoCode.Testing
{
    /// <summary>
    /// AutoTest 生成器 - 自动生成 xUnit 测试桩
    /// </summary>
    [Generator]
    public class TestGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var testSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoTest" || name == "AutoTestAttribute";
                        }),
                    transform: (ctx, _) => GenerateTests(ctx))
                .Where(s => s != null)!;

            context.RegisterSourceOutput(testSources, (spc, source) =>
            {
                spc.AddSource(source!.FileName, SourceText.From(source.SourceText, Encoding.UTF8));
            });
        }

        private static GeneratedSource? GenerateTests(GeneratorSyntaxContext ctx)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "";
            var className = classSymbol.Name;
            var testClassName = $"{className}Tests";

            var methods = classSymbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public)
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .ToList();

            if (methods.Count == 0)
                return null;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Xunit;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// {className} 的自动生成测试（由 AutoCode.Testing 生成）");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public class {testClassName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    private readonly {className} _sut;");
            sb.AppendLine();
            sb.AppendLine($"{indent}    public {testClassName}()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        _sut = new {className}();");
            sb.AppendLine($"{indent}    }}");

            foreach (var method in methods)
            {
                var isAsync = IsAsyncReturn(method.ReturnType);
                var isVoid = method.ReturnType.SpecialType == SpecialType.System_Void;
                var returnTypeShort = GetShortTypeName(method.ReturnType);

                sb.AppendLine();
                sb.AppendLine($"{indent}    [Fact]");

                if (isAsync)
                {
                    sb.AppendLine($"{indent}    public async Task {method.Name}_Should_Complete()");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        // Arrange");
                    GenerateArrange(sb, $"{indent}        ", method);
                    sb.AppendLine($"{indent}        // Act");
                    var awaitArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
                    sb.AppendLine($"{indent}        var result = await _sut.{method.Name}({awaitArgs});");
                    sb.AppendLine($"{indent}        // Assert");
                    sb.AppendLine($"{indent}        Assert.NotNull(result);");
                    sb.AppendLine($"{indent}    }}");
                }
                else if (isVoid)
                {
                    sb.AppendLine($"{indent}    public void {method.Name}_Should_Not_Throw()");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        // Arrange");
                    GenerateArrange(sb, $"{indent}        ", method);
                    sb.AppendLine($"{indent}        // Act & Assert");
                    var args = string.Join(", ", method.Parameters.Select(p => p.Name));
                    sb.AppendLine($"{indent}        var ex = Record.Exception(() => _sut.{method.Name}({args}));");
                    sb.AppendLine($"{indent}        Assert.Null(ex);");
                    sb.AppendLine($"{indent}    }}");
                }
                else
                {
                    sb.AppendLine($"{indent}    public void {method.Name}_Should_Return_{returnTypeShort}()");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        // Arrange");
                    GenerateArrange(sb, $"{indent}        ", method);
                    sb.AppendLine($"{indent}        // Act");
                    var args = string.Join(", ", method.Parameters.Select(p => p.Name));
                    sb.AppendLine($"{indent}        var result = _sut.{method.Name}({args});");
                    sb.AppendLine($"{indent}        // Assert");
                    sb.AppendLine($"{indent}        Assert.NotNull(result);");
                    sb.AppendLine($"{indent}    }}");
                }
            }

            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
                sb.AppendLine("}");

            return new GeneratedSource
            {
                FileName = $"{testClassName}.g.cs",
                SourceText = sb.ToString()
            };
        }

        private static void GenerateArrange(StringBuilder sb, string indent, IMethodSymbol method)
        {
            foreach (var param in method.Parameters)
            {
                var defaultValue = GetDefaultValue(param.Type);
                sb.AppendLine($"{indent}var {param.Name} = {defaultValue};");
            }
        }

        private static string GetDefaultValue(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_Int32: return "0";
                case SpecialType.System_Int64: return "0L";
                case SpecialType.System_String: return "\"test\"";
                case SpecialType.System_Boolean: return "true";
                case SpecialType.System_Double: return "0.0";
                case SpecialType.System_Decimal: return "0m";
                case SpecialType.System_DateTime: return "DateTime.Now";
                default:
                    if (type.IsValueType)
                        return "default";
                    return $"new {type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}()";
            }
        }

        private static bool IsAsyncReturn(ITypeSymbol type)
        {
            if (type is not INamedTypeSymbol named) return false;
            var full = named.OriginalDefinition.ToDisplayString();
            return full.StartsWith("System.Threading.Tasks.Task")
                || full.StartsWith("System.Threading.Tasks.ValueTask");
        }

        private static string GetShortTypeName(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol named && named.IsGenericType)
            {
                var inner = named.TypeArguments.Last();
                return inner.Name;
            }
            return type.Name;
        }
    }

    internal sealed class GeneratedSource
    {
        public string FileName { get; set; } = "";
        public string SourceText { get; set; } = "";
    }
}
