using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoCode.Dto
{
    /// <summary>
    /// AutoDTO 生成器 - 从实体类自动生成 DTO
    /// </summary>
    [Generator]
    public class DtoGenerator : IIncrementalGenerator
    {
        private const string AutoDTOAttributeFullName = "AutoCode.Model.AutoDTOAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var dtoSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoDTO" || name == "AutoDTOAttribute";
                        }),
                    transform: (ctx, _) => GenerateDto(ctx))
                .Where(s => s != null)!;

            context.RegisterSourceOutput(dtoSources, (spc, source) =>
            {
                spc.AddSource(source!.FileName, SourceText.From(source.SourceText, Encoding.UTF8));
            });
        }

        private static GeneratedSource? GenerateDto(GeneratorSyntaxContext ctx)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            // 查找 [AutoDTO] 特性
            var dtoAttr = classSymbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == AutoDTOAttributeFullName
                || a.AttributeClass?.Name == "AutoDTOAttribute");

            if (dtoAttr == null || dtoAttr.ConstructorArguments.Length == 0)
                return null;

            // 获取源类型
            var sourceType = dtoAttr.ConstructorArguments[0].Value as INamedTypeSymbol;
            if (sourceType == null)
                return null;

            // 获取 Include/Exclude 配置
            var includeProps = GetNamedStringArray(dtoAttr, "Include");
            var excludeProps = GetNamedStringArray(dtoAttr, "Exclude");

            // 获取源类型的属性
            var properties = sourceType.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                .Where(p => !p.IsStatic && !p.IsIndexer)
                .Where(p => includeProps == null || includeProps.Contains(p.Name))
                .Where(p => excludeProps == null || !excludeProps.Contains(p.Name))
                .ToList();

            var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "";
            var dtoClassName = classSymbol.Name;
            var sourceTypeName = sourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

            sb.AppendLine($"{indent}public partial class {dtoClassName}");
            sb.AppendLine($"{indent}{{");

            // 生成属性
            foreach (var prop in properties)
            {
                var typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"{indent}    public {typeName} {prop.Name} {{ get; set; }}");
            }

            sb.AppendLine();

            // 生成 FromEntity 方法
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// 从实体创建 DTO");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public static {dtoClassName} FromEntity({sourceTypeName} entity)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        return new {dtoClassName}");
            sb.AppendLine($"{indent}        {{");
            foreach (var prop in properties)
            {
                sb.AppendLine($"{indent}            {prop.Name} = entity.{prop.Name},");
            }
            sb.AppendLine($"{indent}        }};");
            sb.AppendLine($"{indent}    }}");

            sb.AppendLine();

            // 生成 ToEntity 方法
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// 将 DTO 值复制到实体");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public void ToEntity({sourceTypeName} entity)");
            sb.AppendLine($"{indent}    {{");
            foreach (var prop in properties)
            {
                if (prop.SetMethod != null)
                {
                    sb.AppendLine($"{indent}        entity.{prop.Name} = {prop.Name};");
                }
            }
            sb.AppendLine($"{indent}    }}");

            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
                sb.AppendLine("}");

            return new GeneratedSource
            {
                FileName = $"{dtoClassName}.g.cs",
                SourceText = sb.ToString()
            };
        }

        private static HashSet<string>? GetNamedStringArray(AttributeData attr, string name)
        {
            var namedArg = attr.NamedArguments.FirstOrDefault(a => a.Key == name);
            if (namedArg.Value.IsNull)
                return null;

            var values = new HashSet<string>(namedArg.Value.Values
                .Select(v => v.Value as string)
                .Where(s => s != null)
                .Select(s => s!));

            return values.Count > 0 ? values : null;
        }
    }

    internal sealed class GeneratedSource
    {
        public string FileName { get; set; } = "";
        public string SourceText { get; set; } = "";
    }
}
