using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoCode.Validation
{
    /// <summary>
    /// AutoValidator 生成器 - 根据 DataAnnotations 生成编译时验证代码
    /// </summary>
    [Generator]
    public class ValidationGenerator : IIncrementalGenerator
    {
        private const string AutoValidatorAttributeFullName = "AutoCode.Model.AutoValidatorAttribute";

        // 支持的验证特性及其生成的验证逻辑
        private static readonly Dictionary<string, string> ValidationAttributes = new Dictionary<string, string>
        {
            ["Required"] = "Required",
            ["Range"] = "Range",
            ["MaxLength"] = "MaxLength",
            ["MinLength"] = "MinLength",
            ["RegularExpression"] = "RegularExpression",
            ["Email"] = "Email",
            ["Url"] = "Url",
            ["Compare"] = "Compare"
        };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var validatorSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoValidator" || name == "AutoValidatorAttribute";
                        }),
                    transform: (ctx, _) => GenerateValidator(ctx))
                .Where(s => s != null)!;

            context.RegisterSourceOutput(validatorSources, (spc, source) =>
            {
                spc.AddSource(source!.FileName, SourceText.From(source.SourceText, Encoding.UTF8));
            });
        }

        private static GeneratedSource? GenerateValidator(GeneratorSyntaxContext ctx)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "";
            var className = classSymbol.Name;
            var validatorClassName = $"{className}Validator";

            // 收集带验证特性的属性
            var validationRules = new List<(string PropName, string PropType, List<ValidationRule> Rules)>();

            foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
            {
                if (member.DeclaredAccessibility != Accessibility.Public)
                    continue;

                var rules = new List<ValidationRule>();
                foreach (var attr in member.GetAttributes())
                {
                    var attrName = attr.AttributeClass?.Name;
                    if (attrName == null)
                        continue;

                    // 移除 "Attribute" 后缀
                    if (attrName.EndsWith("Attribute"))
                        attrName = attrName.Substring(0, attrName.Length - 9);

                    if (ValidationAttributes.ContainsKey(attrName))
                    {
                        var args = attr.ConstructorArguments
                            .Select(a => a.Value?.ToString() ?? "")
                            .ToList();
                        rules.Add(new ValidationRule(attrName, args));
                    }
                }

                if (rules.Count > 0)
                {
                    validationRules.Add((
                        member.Name,
                        member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        rules));
                }
            }

            if (validationRules.Count == 0)
                return null;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.RegularExpressions;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// {className} 的编译时验证器（由 AutoCode.Validation 自动生成）");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public class {validatorClassName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// 验证实例，返回错误列表（空列表表示验证通过）");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public List<string> Validate({className} input)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var errors = new List<string>();");

            foreach (var (propName, propType, rules) in validationRules)
            {
                foreach (var rule in rules)
                {
                    GenerateValidationCheck(sb, $"{indent}        ", propName, propType, rule);
                }
            }

            sb.AppendLine($"{indent}        return errors;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
                sb.AppendLine("}");

            return new GeneratedSource
            {
                FileName = $"{validatorClassName}.g.cs",
                SourceText = sb.ToString()
            };
        }

        private static void GenerateValidationCheck(StringBuilder sb, string indent, string propName, string propType, ValidationRule rule)
        {
            switch (rule.Name)
            {
                case "Required":
                    if (propType == "string" || propType.Contains("string"))
                        sb.AppendLine($"{indent}if (string.IsNullOrEmpty(input.{propName})) errors.Add(\"{propName} is required.\");");
                    else
                        sb.AppendLine($"{indent}if (input.{propName} == null) errors.Add(\"{propName} is required.\");");
                    break;

                case "MaxLength" when rule.Args.Count > 0:
                    sb.AppendLine($"{indent}if (input.{propName}?.Length > {rule.Args[0]}) errors.Add(\"{propName} must not exceed {rule.Args[0]} characters.\");");
                    break;

                case "MinLength" when rule.Args.Count > 0:
                    sb.AppendLine($"{indent}if (input.{propName}?.Length < {rule.Args[0]}) errors.Add(\"{propName} must be at least {rule.Args[0]} characters.\");");
                    break;

                case "Range" when rule.Args.Count >= 2:
                    sb.AppendLine($"{indent}if (input.{propName} < {rule.Args[0]} || input.{propName} > {rule.Args[1]}) errors.Add(\"{propName} must be between {rule.Args[0]} and {rule.Args[1]}.\");");
                    break;

                case "RegularExpression" when rule.Args.Count > 0:
                    sb.AppendLine($"{indent}if (input.{propName} != null && !Regex.IsMatch(input.{propName}, @\"{rule.Args[0]}\")) errors.Add(\"{propName} format is invalid.\");");
                    break;

                case "Email":
                    sb.AppendLine($"{indent}if (input.{propName} != null && !input.{propName}.Contains(\"@\")) errors.Add(\"{propName} must be a valid email address.\");");
                    break;

                case "Url":
                    sb.AppendLine($"{indent}if (input.{propName} != null && !Uri.TryCreate(input.{propName}, UriKind.Absolute, out _)) errors.Add(\"{propName} must be a valid URL.\");");
                    break;
            }
        }
    }

    internal sealed class ValidationRule
    {
        public string Name { get; }
        public List<string> Args { get; }

        public ValidationRule(string name, List<string> args)
        {
            Name = name;
            Args = args;
        }
    }

    internal sealed class GeneratedSource
    {
        public string FileName { get; set; } = "";
        public string SourceText { get; set; } = "";
    }
}
