using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using AutoCode.Engine.CodeBuilder;

namespace AutoCode.Plugins.Crud
{
    /// <summary>
    /// CRUD 一键生成器 - 从实体类生成完整 CRUD 栈：
    /// IRepository 接口 + EF Core 实现 + IService 接口 + Service + Controller。
    /// 支持软删除、审计日志、分页查询。
    /// </summary>
    [Generator]
    public class CrudGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var crudSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoCrud" || name == "AutoCrudAttribute";
                        }),
                    transform: static (ctx, ct) => ExtractEntityInfo(ctx, ct))
                .Where(static s => s != null)
                .SelectMany(static (info, _) => GenerateAllFiles(info!));

            context.RegisterSourceOutput(crudSources, static (spc, file) =>
            {
                spc.AddSource(file.FileName, SourceText.From(file.Content, Encoding.UTF8));
            });
        }

        private static EntityInfo? ExtractEntityInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var entitySymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
            if (entitySymbol == null)
                return null;

            var attr = entitySymbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.Name == "AutoCrudAttribute" || a.AttributeClass?.Name == "AutoCrud");

            // 获取主键
            var keyProp = entitySymbol.GetMembers().OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == "Id");
            var keyType = keyProp?.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat) ?? "int";

            // 获取属性
            var properties = entitySymbol.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public)
                .Where(p => !p.IsStatic && !p.IsIndexer)
                .Select(p => new PropInfo
                {
                    Name = p.Name,
                    Type = p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                })
                .ToList();

            // 检测软删除和审计
            var hasSoftDelete = entitySymbol.GetAttributes().Any(a => a.AttributeClass?.Name == "SoftDeleteAttribute");
            var hasAudit = entitySymbol.GetAttributes().Any(a => a.AttributeClass?.Name == "AuditableAttribute");

            // 路由
            var routePrefix = attr?.NamedArguments
                .FirstOrDefault(a => a.Key == "RoutePrefix").Value.Value as string;

            return new EntityInfo
            {
                Name = entitySymbol.Name,
                FullName = entitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                Namespace = entitySymbol.ContainingNamespace?.ToDisplayString() ?? "",
                KeyType = keyType,
                Properties = properties,
                HasSoftDelete = hasSoftDelete,
                HasAudit = hasAudit,
                RoutePrefix = routePrefix ?? $"api/{entitySymbol.Name.ToLowerInvariant()}s"
            };
        }

        private static List<CrudFile> GenerateAllFiles(EntityInfo entity)
        {
            var files = new List<CrudFile>();

            files.Add(GenerateIRepository(entity));
            files.Add(GenerateRepository(entity));
            files.Add(GenerateIService(entity));
            files.Add(GenerateService(entity));
            files.Add(GenerateController(entity));

            return files;
        }

        private static CrudFile GenerateIRepository(EntityInfo e)
        {
            var w = new CodeWriter();
            w.AutoGeneratedHeader();
            w.Using("System", "System.Collections.Generic", "System.Linq.Expressions", "System.Threading.Tasks");
            w.FileScopedNamespace(e.Namespace);

            w.Interface($"I{e.Name}Repository", c =>
            {
                c.Public();
                c.Doc($"{e.Name} 仓储接口（由 AutoCode CRUD 自动生成）");

                c.Method("GetAllAsync", m => m
                    .Returns($"Task<List<{e.Name}>>")
                    .Doc("获取所有记录"));
                c.Method("GetByIdAsync", m => m
                    .Parameter(e.KeyType, "id")
                    .Returns($"Task<{e.Name}?>")
                    .Doc("根据 ID 获取"));
                c.Method("FindAsync", m => m
                    .Parameter($"Expression<Func<{e.Name}, bool>>", "predicate")
                    .Returns($"Task<List<{e.Name}>>")
                    .Doc("条件查询"));
                c.Method("GetPagedAsync", m => m
                    .Parameter("int", "page")
                    .Parameter("int", "pageSize")
                    .Parameter($"Expression<Func<{e.Name}, bool>>?", "filter", "null")
                    .Returns($"Task<(List<{e.Name}> Items, int Total)>")
                    .Doc("分页查询"));
                c.Method("AddAsync", m => m
                    .Parameter(e.Name, "entity")
                    .Returns($"Task<{e.Name}>")
                    .Doc("新增"));
                c.Method("UpdateAsync", m => m
                    .Parameter(e.Name, "entity")
                    .Returns($"Task<{e.Name}?>")
                    .Doc("更新"));
                c.Method("DeleteAsync", m => m
                    .Parameter(e.KeyType, "id")
                    .Returns("Task<bool>")
                    .Doc("删除"));
                c.Method("CountAsync", m => m
                    .Returns("Task<int>")
                    .Doc("获取总数"));
            });

            return new CrudFile { FileName = $"I{e.Name}Repository.g.cs", Content = w.Build() };
        }

        private static CrudFile GenerateRepository(EntityInfo e)
        {
            var w = new CodeWriter();
            w.AutoGeneratedHeader();
            w.Using("System", "System.Collections.Generic", "System.Linq",
                "System.Linq.Expressions", "System.Threading.Tasks",
                "Microsoft.EntityFrameworkCore");
            w.FileScopedNamespace(e.Namespace);

            w.Class($"{e.Name}Repository", c =>
            {
                c.Public();
                c.Implements($"I{e.Name}Repository");
                c.Doc($"{e.Name} EF Core 仓储实现（由 AutoCode CRUD 自动生成）");

                c.Field("_context", f => f.Private().ReadOnly().Type("DbContext"));
                c.Field("_dbSet", f => f.Private().ReadOnly().Type($"DbSet<{e.Name}>"));

                c.Constructor(ctor =>
                {
                    ctor.AssignField("DbContext", "context", "_context");
                    ctor.Body("_dbSet = _context.Set<" + e.Name + ">();");
                });

                // GetAllAsync
                c.Method("GetAllAsync", m => m.Public().Async()
                    .Returns($"Task<List<{e.Name}>>")
                    .Body(b =>
                    {
                        if (e.HasSoftDelete)
                            b.Return("await _dbSet.Where(x => !x.IsDeleted).ToListAsync()");
                        else
                            b.Return("await _dbSet.ToListAsync()");
                    }));

                // GetByIdAsync
                c.Method("GetByIdAsync", m => m.Public().Async()
                    .Parameter(e.KeyType, "id")
                    .Returns($"Task<{e.Name}?>")
                    .Body(b => b.Return("await _dbSet.FindAsync(id)")));

                // FindAsync
                c.Method("FindAsync", m => m.Public().Async()
                    .Parameter($"Expression<Func<{e.Name}, bool>>", "predicate")
                    .Returns($"Task<List<{e.Name}>>")
                    .Body(b => b.Return("await _dbSet.Where(predicate).ToListAsync()")));

                // GetPagedAsync
                c.Method("GetPagedAsync", m => m.Public().Async()
                    .Parameter("int", "page")
                    .Parameter("int", "pageSize")
                    .Parameter($"Expression<Func<{e.Name}, bool>>?", "filter", "null")
                    .Returns($"Task<(List<{e.Name}> Items, int Total)>")
                    .Body(b =>
                    {
                        b.Var("query", "_dbSet.AsQueryable()");
                        if (e.HasSoftDelete)
                            b.Line("query = query.Where(x => !x.IsDeleted);");
                        b.Line("if (filter != null) query = query.Where(filter);");
                        b.Var("total", "await query.CountAsync()");
                        b.Var("items", "await query.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync()");
                        b.Return("(items, total)");
                    }));

                // AddAsync
                c.Method("AddAsync", m => m.Public().Async()
                    .Parameter(e.Name, "entity")
                    .Returns($"Task<{e.Name}>")
                    .Body(b =>
                    {
                        if (e.HasAudit)
                        {
                            b.Line("entity.CreatedAt = DateTime.UtcNow;");
                        }
                        b.Line("await _dbSet.AddAsync(entity);");
                        b.Line("await _context.SaveChangesAsync();");
                        b.Return("entity");
                    }));

                // UpdateAsync
                c.Method("UpdateAsync", m => m.Public().Async()
                    .Parameter(e.Name, "entity")
                    .Returns($"Task<{e.Name}?>")
                    .Body(b =>
                    {
                        b.Var("existing", "await _dbSet.FindAsync(entity.Id)");
                        b.If("existing == null").Return("null").End();
                        if (e.HasAudit)
                            b.Line("entity.ModifiedAt = DateTime.UtcNow;");
                        b.Line("_context.Entry(existing).CurrentValues.SetValues(entity);");
                        b.Line("await _context.SaveChangesAsync();");
                        b.Return("existing");
                    }));

                // DeleteAsync
                c.Method("DeleteAsync", m => m.Public().Async()
                    .Parameter(e.KeyType, "id")
                    .Returns("Task<bool>")
                    .Body(b =>
                    {
                        b.Var("entity", "await _dbSet.FindAsync(id)");
                        b.If("entity == null").Return("false").End();
                        if (e.HasSoftDelete)
                        {
                            b.Line("entity.IsDeleted = true;");
                            b.Line("entity.DeletedAt = DateTime.UtcNow;");
                        }
                        else
                        {
                            b.Line("_dbSet.Remove(entity);");
                        }
                        b.Line("await _context.SaveChangesAsync();");
                        b.Return("true");
                    }));

                // CountAsync
                c.Method("CountAsync", m => m.Public().Async()
                    .Returns("Task<int>")
                    .Body(b =>
                    {
                        if (e.HasSoftDelete)
                            b.Return("await _dbSet.CountAsync(x => !x.IsDeleted)");
                        else
                            b.Return("await _dbSet.CountAsync()");
                    }));
            });

            return new CrudFile { FileName = $"{e.Name}Repository.g.cs", Content = w.Build() };
        }

        private static CrudFile GenerateIService(EntityInfo e)
        {
            var w = new CodeWriter();
            w.AutoGeneratedHeader();
            w.Using("System.Collections.Generic", "System.Threading.Tasks");
            w.FileScopedNamespace(e.Namespace);

            w.Interface($"I{e.Name}Service", c =>
            {
                c.Public();
                c.Doc($"{e.Name} 服务接口");
                c.Method("GetAllAsync", m => m.Returns($"Task<List<{e.Name}>>"));
                c.Method("GetByIdAsync", m => m.Parameter(e.KeyType, "id").Returns($"Task<{e.Name}?>"));
                c.Method("GetPagedAsync", m => m
                    .Parameter("int", "page", "1")
                    .Parameter("int", "pageSize", "20")
                    .Returns($"Task<(List<{e.Name}> Items, int Total)>"));
                c.Method("CreateAsync", m => m.Parameter(e.Name, "entity").Returns($"Task<{e.Name}>"));
                c.Method("UpdateAsync", m => m.Parameter(e.KeyType, "id").Parameter(e.Name, "entity").Returns($"Task<{e.Name}?>"));
                c.Method("DeleteAsync", m => m.Parameter(e.KeyType, "id").Returns("Task<bool>"));
            });

            return new CrudFile { FileName = $"I{e.Name}Service.g.cs", Content = w.Build() };
        }

        private static CrudFile GenerateService(EntityInfo e)
        {
            var w = new CodeWriter();
            w.AutoGeneratedHeader();
            w.Using("System", "System.Collections.Generic", "System.Threading.Tasks");
            w.FileScopedNamespace(e.Namespace);

            w.Class($"{e.Name}Service", c =>
            {
                c.Public();
                c.Implements($"I{e.Name}Service");
                c.Doc($"{e.Name} 服务实现（由 AutoCode CRUD 自动生成）");

                c.Field("_repository", f => f.Private().ReadOnly().Type($"I{e.Name}Repository"));
                c.Constructor(ctor => ctor.AssignField($"I{e.Name}Repository", "repository", "_repository"));

                c.Method("GetAllAsync", m => m.Public().Async()
                    .Returns($"Task<List<{e.Name}>>")
                    .Body(b => b.Return("await _repository.GetAllAsync()")));

                c.Method("GetByIdAsync", m => m.Public().Async()
                    .Parameter(e.KeyType, "id")
                    .Returns($"Task<{e.Name}?>")
                    .Body(b => b.Return("await _repository.GetByIdAsync(id)")));

                c.Method("GetPagedAsync", m => m.Public().Async()
                    .Parameter("int", "page", "1")
                    .Parameter("int", "pageSize", "20")
                    .Returns($"Task<(List<{e.Name}> Items, int Total)>")
                    .Body(b => b.Return("await _repository.GetPagedAsync(page, pageSize)")));

                c.Method("CreateAsync", m => m.Public().Async()
                    .Parameter(e.Name, "entity")
                    .Returns($"Task<{e.Name}>")
                    .Body(b => b.Return("await _repository.AddAsync(entity)")));

                c.Method("UpdateAsync", m => m.Public().Async()
                    .Parameter(e.KeyType, "id")
                    .Parameter(e.Name, "entity")
                    .Returns($"Task<{e.Name}?>")
                    .Body(b =>
                    {
                        b.Line("entity.Id = id;");
                        b.Return("await _repository.UpdateAsync(entity)");
                    }));

                c.Method("DeleteAsync", m => m.Public().Async()
                    .Parameter(e.KeyType, "id")
                    .Returns("Task<bool>")
                    .Body(b => b.Return("await _repository.DeleteAsync(id)")));
            });

            return new CrudFile { FileName = $"{e.Name}Service.g.cs", Content = w.Build() };
        }

        private static CrudFile GenerateController(EntityInfo e)
        {
            var w = new CodeWriter();
            w.AutoGeneratedHeader();
            w.Using("System.Collections.Generic", "System.Threading.Tasks", "Microsoft.AspNetCore.Mvc");
            w.FileScopedNamespace(e.Namespace);

            w.Class($"{e.Name}sController", c =>
            {
                c.Public();
                c.Attribute("ApiController");
                c.Attribute($"Route(\"{e.RoutePrefix}\")");
                c.Attribute("Produces(\"application/json\")");
                c.Doc($"{e.Name} CRUD Controller（由 AutoCode 自动生成）");

                c.Field("_service", f => f.Private().ReadOnly().Type($"I{e.Name}Service"));
                c.Constructor(ctor => ctor.AssignField($"I{e.Name}Service", "service", "_service"));

                // GET all
                c.Method("GetAll", m => m.Public().Async()
                    .Attribute("HttpGet")
                    .Attribute($"ProducesResponseType(typeof(List<{e.Name}>), 200)")
                    .Returns($"ActionResult<List<{e.Name}>>")
                    .Body(b => b.Return("Ok(await _service.GetAllAsync())")));

                // GET by id
                c.Method("GetById", m => m.Public().Async()
                    .Attribute("HttpGet(\"{id}\")")
                    .Attribute($"ProducesResponseType(typeof({e.Name}), 200)")
                    .Attribute("ProducesResponseType(404)")
                    .Parameter(e.KeyType, "id")
                    .Returns($"ActionResult<{e.Name}>")
                    .Body(b =>
                    {
                        b.Var("result", "await _service.GetByIdAsync(id)");
                        b.Return("result == null ? NotFound() : Ok(result)");
                    }));

                // GET paged
                c.Method("GetPaged", m => m.Public().Async()
                    .Attribute("HttpGet(\"paged\")")
                    .Parameter("int", "page", "1")
                    .Parameter("int", "pageSize", "20")
                    .Returns("ActionResult")
                    .Body(b =>
                    {
                        b.Var("(items, total)", "await _service.GetPagedAsync(page, pageSize)");
                        b.Return("Ok(new { items, total, page, pageSize })");
                    }));

                // POST
                c.Method("Create", m => m.Public().Async()
                    .Attribute("HttpPost")
                    .Attribute($"ProducesResponseType(typeof({e.Name}), 201)")
                    .Parameter(e.Name, "entity", "FromBody")
                    .Returns($"ActionResult<{e.Name}>")
                    .Body(b =>
                    {
                        b.Var("result", "await _service.CreateAsync(entity)");
                        b.Return("CreatedAtAction(nameof(GetById), new { id = result.Id }, result)");
                    }));

                // PUT
                c.Method("Update", m => m.Public().Async()
                    .Attribute("HttpPut(\"{id}\")")
                    .Attribute($"ProducesResponseType(typeof({e.Name}), 200)")
                    .Attribute("ProducesResponseType(404)")
                    .Parameter(e.KeyType, "id")
                    .Parameter(e.Name, "entity", "FromBody")
                    .Returns($"ActionResult<{e.Name}>")
                    .Body(b =>
                    {
                        b.Var("result", "await _service.UpdateAsync(id, entity)");
                        b.Return("result == null ? NotFound() : Ok(result)");
                    }));

                // DELETE
                c.Method("Delete", m => m.Public().Async()
                    .Attribute("HttpDelete(\"{id}\")")
                    .Attribute("ProducesResponseType(204)")
                    .Attribute("ProducesResponseType(404)")
                    .Parameter(e.KeyType, "id")
                    .Returns("IActionResult")
                    .Body(b => b.Return("await _service.DeleteAsync(id) ? NoContent() : NotFound()")));
            });

            return new CrudFile { FileName = $"{e.Name}sController.g.cs", Content = w.Build() };
        }
    }

    #region Models

    internal sealed class EntityInfo
    {
        public string Name { get; set; } = "";
        public string FullName { get; set; } = "";
        public string Namespace { get; set; } = "";
        public string KeyType { get; set; } = "int";
        public List<PropInfo> Properties { get; set; } = new List<PropInfo>();
        public bool HasSoftDelete { get; set; }
        public bool HasAudit { get; set; }
        public string RoutePrefix { get; set; } = "";
    }

    internal sealed class PropInfo
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
    }

    internal sealed class CrudFile
    {
        public string FileName { get; set; } = "";
        public string Content { get; set; } = "";
    }

    #endregion
}
