using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using AutoCode.Engine.CodeBuilder;

namespace AutoCode.Plugins.Logging
{
    /// <summary>
    /// 日志装饰器生成器 v2 - 结构化日志 + 耗时统计 + 异常捕获 + 敏感参数脱敏。
    /// </summary>
    [Generator]
    public class LogDecoratorGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var logSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoLog" || name == "AutoLogAttribute";
                        }),
                    transform: static (ctx, ct) => ExtractLogInfo(ctx, ct))
                .Where(static s => s != null);

            context.RegisterSourceOutput(AutoCode.Generators.V2Gate.Apply(context, logSources), static (spc, info) =>
            {
                var output = GenerateDecorator(info!);
                if (output != null)
                    spc.AddSource(output.FileName, SourceText.From(output.Content, Encoding.UTF8));
            });
        }

        private static LogInfo? ExtractLogInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            var serviceInterface = classSymbol.Interfaces
                .FirstOrDefault(i => i.Name != "IScoped" && i.Name != "ISingleton"
                    && i.Name != "ITransient" && i.Name != "IDependencyBase");

            if (serviceInterface == null)
                return null;

            var methods = serviceInterface.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .Select(m => new LogMethodInfo
                {
                    Name = m.Name,
                    ReturnType = m.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    IsAsync = IsAsyncReturn(m.ReturnType),
                    IsVoid = m.ReturnType.SpecialType == SpecialType.System_Void,
                    IsTaskNoResult = m.ReturnType.ToDisplayString() == "System.Threading.Tasks.Task",
                    Parameters = m.Parameters.Select(p => new LogParamInfo
                    {
                        Name = p.Name,
                        Type = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        IsSensitive = p.GetAttributes().Any(a => a.AttributeClass?.Name == "SensitiveAttribute")
                    }).ToList()
                })
                .ToList();

            return new LogInfo
            {
                ClassName = classSymbol.Name,
                Namespace = classSymbol.ContainingNamespace?.ToDisplayString() ?? "",
                InterfaceName = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                Methods = methods
            };
        }

        private static LogOutput? GenerateDecorator(LogInfo info)
        {
            var decoratorName = $"Logging{info.ClassName}";
            var w = new CodeWriter();
            w.AutoGeneratedHeader();
            w.Using("System", "System.Diagnostics", "System.Threading.Tasks",
                "Microsoft.Extensions.Logging");
            w.FileScopedNamespace(info.Namespace);

            w.Class(decoratorName, c =>
            {
                c.Public();
                c.Implements(info.InterfaceName);
                c.Doc($"{info.ClassName} 的日志装饰器（由 AutoCode Logging 插件自动生成）",
                    "功能：结构化日志、耗时统计、异常捕获、敏感参数脱敏");

                c.Field("_inner", f => f.Private().ReadOnly().Type(info.InterfaceName));
                c.Field("_logger", f => f.Private().ReadOnly().Type($"ILogger<{decoratorName}>"));

                c.Constructor(ctor =>
                {
                    ctor.AssignField(info.InterfaceName, "inner", "_inner");
                    ctor.AssignField($"ILogger<{decoratorName}>", "logger", "_logger");
                });

                foreach (var method in info.Methods)
                {
                    GenerateMethod(c, method, decoratorName);
                }
            });

            return new LogOutput
            {
                FileName = $"{decoratorName}.g.cs",
                Content = w.Build()
            };
        }

        private static void GenerateMethod(ClassBuilder c, LogMethodInfo method, string decoratorName)
        {
            c.Method(method.Name, m =>
            {
                m.Public();
                if (method.IsAsync) m.Async();

                // 参数
                foreach (var param in method.Parameters)
                    m.Parameter(param.Type, param.Name);

                m.Returns(method.ReturnType);

                // 构建结构化日志参数
                var logParams = method.Parameters
                    .Where(p => !p.IsSensitive)
                    .Select(p => $"{p.Name} = {{{p.Name}}}")
                    .ToList();
                var logArgs = method.Parameters
                    .Where(p => !p.IsSensitive)
                    .Select(p => p.Name)
                    .ToList();

                var sensitiveParams = method.Parameters.Where(p => p.IsSensitive).ToList();
                if (sensitiveParams.Count > 0)
                {
                    logParams.Add("[SensitiveParams={SensitiveCount}]");
                    logArgs.Add(sensitiveParams.Count.ToString());
                }

                var logParamStr = logParams.Count > 0 ? ", " + string.Join(", ", logParams) : "";
                var logArgStr = logArgs.Count > 0 ? ", " + string.Join(", ", logArgs) : "";
                var args = string.Join(", ", method.Parameters.Select(p => p.Name));

                m.Body(b =>
                {
                    b.Line($"_logger.LogInformation(\"{method.Name} 开始{logParamStr}\"{logArgStr});");
                    b.Var("sw", "Stopwatch.StartNew()");
                    b.Line("try");
                    b.Line("{");

                    if (method.IsAsync)
                    {
                        if (method.IsTaskNoResult || method.IsVoid)
                        {
                            b.Line($"    await _inner.{method.Name}({args});");
                            b.Line($"    _logger.LogInformation(\"{method.Name} 完成, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                        }
                        else
                        {
                            b.Line($"    var result = await _inner.{method.Name}({args});");
                            b.Line($"    _logger.LogInformation(\"{method.Name} 完成, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                            b.Line("    return result;");
                        }
                    }
                    else if (method.IsVoid)
                    {
                        b.Line($"    _inner.{method.Name}({args});");
                        b.Line($"    _logger.LogInformation(\"{method.Name} 完成, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                    }
                    else
                    {
                        b.Line($"    var result = _inner.{method.Name}({args});");
                        b.Line($"    _logger.LogInformation(\"{method.Name} 完成, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                        b.Line("    return result;");
                    }

                    b.Line("}");
                    b.Line("catch (Exception ex)");
                    b.Line("{");
                    b.Line($"    _logger.LogError(ex, \"{method.Name} 异常, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                    b.Line("    throw;");
                    b.Line("}");
                });
            });
        }

        private static bool IsAsyncReturn(ITypeSymbol type)
        {
            if (type is not INamedTypeSymbol named) return false;
            var full = named.OriginalDefinition.ToDisplayString();
            return full.StartsWith("System.Threading.Tasks.Task")
                || full.StartsWith("System.Threading.Tasks.ValueTask");
        }
    }

    #region Models

    internal sealed class LogInfo
    {
        public string ClassName { get; set; } = "";
        public string Namespace { get; set; } = "";
        public string InterfaceName { get; set; } = "";
        public List<LogMethodInfo> Methods { get; set; } = new List<LogMethodInfo>();
    }

    internal sealed class LogMethodInfo
    {
        public string Name { get; set; } = "";
        public string ReturnType { get; set; } = "";
        public bool IsAsync { get; set; }
        public bool IsVoid { get; set; }
        public bool IsTaskNoResult { get; set; }
        public List<LogParamInfo> Parameters { get; set; } = new List<LogParamInfo>();
    }

    internal sealed class LogParamInfo
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
        public bool IsSensitive { get; set; }
    }

    internal sealed class LogOutput
    {
        public string FileName { get; set; } = "";
        public string Content { get; set; } = "";
    }

    #endregion
}
