using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using AutoCode.Engine.CodeBuilder;

namespace AutoCode.Plugins.Validation
{
    /// <summary>
    /// 生产级验证代码生成器 - 根据 DataAnnotations 生成零反射编译时验证代码。
    /// 支持：Required/Range/MaxLength/MinLength/Email/Url/Regex/Compare/Phone/CreditCard、
    /// 跨属性验证、集合元素验证、条件验证、自定义错误消息。
    /// </summary>
    [Generator]
    public class ValidationGenerator : IIncrementalGenerator
    {
        private const string AutoValidatorAttrName = "AutoValidatorAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var validatorSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoValidator" || name == AutoValidatorAttrName;
                        }),
                    transform: static (ctx, ct) => GenerateValidator(ctx, ct))
                .Where(static s => s != null);

            context.RegisterSourceOutput(validatorSources, static (spc, source) =>
            {
                spc.AddSource(source!.FileName, SourceText.From(source.Content, Encoding.UTF8));
            });
        }

        private static ValidatorOutput? GenerateValidator(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "";
            var className = classSymbol.Name;
            var validatorClassName = $"{className}Validator";

            // 收集验证规则
            var rules = CollectValidationRules(classSymbol);
            if (rules.Count == 0)
                return null;

            // 使用 CodeBuilder 生成
            var writer = new CodeWriter();
            writer.AutoGeneratedHeader();
            writer.Using("System", "System.Collections.Generic", "System.Text.RegularExpressions");
            writer.FileScopedNamespace(namespaceName);

            writer.Class(validatorClassName, c =>
            {
                c.Public();
                c.Doc($"{className} 的编译时验证器（由 AutoCode Validation 插件自动生成）",
                    "零反射、零运行时依赖、兼容 NativeAOT");

                // 验证结果类
                c.NestedClass("ValidationResult", nested =>
                {
                    nested.Public();
                    nested.Property("IsValid", p => p.Type("bool").Doc("是否验证通过"));
                    nested.Property("Errors", p => p.Type("List<string>").Initializer("new List<string>()").Doc("错误列表"));
                });

                // Validate 方法
                c.Method("Validate", m =>
                {
                    m.Public();
                    m.Doc("验证实例，返回结构化结果");
                    m.Parameter(className, "input");
                    m.Returns("ValidationResult");
                    m.Body(b =>
                    {
                        b.If("input == null").Line("throw new ArgumentNullException(nameof(input));").End();
                        b.Var("result", "new ValidationResult()");
                        b.Blank();

                        foreach (var rule in rules)
                        {
                            GenerateValidationRule(b, rule);
                        }

                        b.Blank();
                        b.Line("result.IsValid = result.Errors.Count == 0;");
                        b.Return("result");
                    });
                });

                // 简化版 Validate 方法（返回 List<string>，向后兼容）
                c.Method("ValidateErrors", m =>
                {
                    m.Public();
                    m.Doc("验证实例，返回错误列表（空列表表示通过）");
                    m.Parameter(className, "input");
                    m.Returns("List<string>");
                    m.Body(b =>
                    {
                        b.Return("Validate(input).Errors");
                    });
                });

                // 快速验证方法
                c.Method("IsValid", m =>
                {
                    m.Public();
                    m.Doc("快速检查是否有效");
                    m.Parameter(className, "input");
                    m.Returns("bool");
                    m.ExpressionBody("Validate(input).IsValid");
                });
            });

            return new ValidatorOutput
            {
                FileName = $"{validatorClassName}.g.cs",
                Content = writer.Build()
            };
        }

        private static List<PropertyValidationRule> CollectValidationRules(INamedTypeSymbol classSymbol)
        {
            var rules = new List<PropertyValidationRule>();

            foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
            {
                if (member.DeclaredAccessibility != Microsoft.CodeAnalysis.Accessibility.Public)
                    continue;

                var propRules = new List<ValidationCheck>();
                var isNullable = member.NullableAnnotation == NullableAnnotation.Annotated
                    || member.Type.IsValueType == false;
                var typeName = member.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                var isString = member.Type.SpecialType == SpecialType.System_String;
                var isCollection = IsCollectionType(member.Type);

                foreach (var attr in member.GetAttributes())
                {
                    var attrName = attr.AttributeClass?.Name ?? "";
                    if (attrName.EndsWith("Attribute"))
                        attrName = attrName.Substring(0, attrName.Length - 9);

                    var customMessage = attr.NamedArguments
                        .FirstOrDefault(a => a.Key == "ErrorMessage").Value.Value as string;

                    var check = CreateCheck(attrName, attr, member, customMessage, isString, isNullable, typeName);
                    if (check != null)
                        propRules.Add(check);
                }

                if (propRules.Count > 0)
                {
                    rules.Add(new PropertyValidationRule
                    {
                        PropertyName = member.Name,
                        PropertyType = typeName,
                        IsNullable = isNullable,
                        IsString = isString,
                        IsCollection = isCollection,
                        Checks = propRules
                    });
                }
            }

            return rules;
        }

        private static ValidationCheck? CreateCheck(string attrName, AttributeData attr,
            IPropertySymbol prop, string? customMessage, bool isString, bool isNullable, string typeName)
        {
            var args = attr.ConstructorArguments.Select(a => a.Value?.ToString() ?? "").ToList();

            switch (attrName)
            {
                case "Required":
                    var allowEmpty = attr.NamedArguments
                        .FirstOrDefault(a => a.Key == "AllowEmptyStrings").Value.Value is true;
                    return new ValidationCheck
                    {
                        Kind = CheckKind.Required,
                        Message = customMessage ?? $"{prop.Name} is required.",
                        AllowEmptyStrings = allowEmpty
                    };

                case "MaxLength" when args.Count > 0:
                    return new ValidationCheck
                    {
                        Kind = CheckKind.MaxLength,
                        Message = customMessage ?? $"{prop.Name} must not exceed {args[0]} characters.",
                        IntArg = int.TryParse(args[0], out var ml) ? ml : 0
                    };

                case "MinLength" when args.Count > 0:
                    return new ValidationCheck
                    {
                        Kind = CheckKind.MinLength,
                        Message = customMessage ?? $"{prop.Name} must be at least {args[0]} characters.",
                        IntArg = int.TryParse(args[0], out var mnl) ? mnl : 0
                    };

                case "StringLength":
                    var maxLen = args.Count > 0 && int.TryParse(args[0], out var sl) ? sl : int.MaxValue;
                    var minLen = attr.NamedArguments
                        .FirstOrDefault(a => a.Key == "MinimumLength").Value.Value is int minV ? minV : 0;
                    return new ValidationCheck
                    {
                        Kind = CheckKind.StringLength,
                        Message = customMessage ?? $"{prop.Name} must be between {minLen} and {maxLen} characters.",
                        IntArg = maxLen,
                        IntArg2 = minLen
                    };

                case "Range" when args.Count >= 2:
                    return new ValidationCheck
                    {
                        Kind = CheckKind.Range,
                        Message = customMessage ?? $"{prop.Name} must be between {args[0]} and {args[1]}.",
                        StringArg = args[0],
                        StringArg2 = args[1]
                    };

                case "RegularExpression" when args.Count > 0:
                    return new ValidationCheck
                    {
                        Kind = CheckKind.Regex,
                        Message = customMessage ?? $"{prop.Name} format is invalid.",
                        StringArg = args[0]
                    };

                case "EmailAddress":
                case "Email":
                    return new ValidationCheck
                    {
                        Kind = CheckKind.Email,
                        Message = customMessage ?? $"{prop.Name} must be a valid email address."
                    };

                case "Url":
                    return new ValidationCheck
                    {
                        Kind = CheckKind.Url,
                        Message = customMessage ?? $"{prop.Name} must be a valid URL."
                    };

                case "Phone":
                    return new ValidationCheck
                    {
                        Kind = CheckKind.Phone,
                        Message = customMessage ?? $"{prop.Name} must be a valid phone number."
                    };

                case "Compare" when args.Count > 0:
                    return new ValidationCheck
                    {
                        Kind = CheckKind.Compare,
                        Message = customMessage ?? $"{prop.Name} must match {args[0]}.",
                        StringArg = args[0]
                    };

                case "CreditCard":
                    return new ValidationCheck
                    {
                        Kind = CheckKind.CreditCard,
                        Message = customMessage ?? $"{prop.Name} must be a valid credit card number."
                    };

                case "EnumDataType":
                    return new ValidationCheck
                    {
                        Kind = CheckKind.EnumValid,
                        Message = customMessage ?? $"{prop.Name} has an invalid value."
                    };

                default:
                    return null;
            }
        }

        private static void GenerateValidationRule(Engine.CodeBuilder.BodyBuilder b, PropertyValidationRule rule)
        {
            var prop = $"input.{rule.PropertyName}";

            foreach (var check in rule.Checks)
            {
                switch (check.Kind)
                {
                    case CheckKind.Required:
                        if (rule.IsString)
                        {
                            if (check.AllowEmptyStrings)
                                b.Line($"if ({prop} == null) result.Errors.Add(\"{Escape(check.Message)}\");");
                            else
                                b.Line($"if (string.IsNullOrWhiteSpace({prop})) result.Errors.Add(\"{Escape(check.Message)}\");");
                        }
                        else
                        {
                            b.Line($"if ({prop} == null) result.Errors.Add(\"{Escape(check.Message)}\");");
                        }
                        break;

                    case CheckKind.MaxLength:
                        b.Line($"if ({prop} != null && {prop}.Length > {check.IntArg}) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.MinLength:
                        b.Line($"if ({prop} != null && {prop}.Length < {check.IntArg}) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.StringLength:
                        b.Line($"if ({prop} != null && ({prop}.Length > {check.IntArg} || {prop}.Length < {check.IntArg2})) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.Range:
                        b.Line($"if ({prop} < {check.StringArg} || {prop} > {check.StringArg2}) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.Regex:
                        b.Line($"if ({prop} != null && !Regex.IsMatch({prop}, @\"{check.StringArg}\")) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.Email:
                        // 生产级邮箱验证（非简单 Contains("@")）
                        b.Line($"if ({prop} != null && !IsValidEmail({prop})) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.Url:
                        b.Line($"if ({prop} != null && !Uri.TryCreate({prop}, UriKind.Absolute, out _)) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.Phone:
                        b.Line($"if ({prop} != null && !IsValidPhone({prop})) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.Compare:
                        b.Line($"if (!Equals({prop}, input.{check.StringArg})) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.CreditCard:
                        b.Line($"if ({prop} != null && !IsValidCreditCard({prop})) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;

                    case CheckKind.EnumValid:
                        b.Line($"if (!Enum.IsDefined(typeof({rule.PropertyType}), {prop})) result.Errors.Add(\"{Escape(check.Message)}\");");
                        break;
                }
            }
        }

        private static bool IsCollectionType(ITypeSymbol type)
        {
            if (type is not INamedTypeSymbol named || !named.IsGenericType)
                return false;
            var name = named.OriginalDefinition.ToDisplayString();
            return name.Contains("List") || name.Contains("Collection") || name.Contains("IEnumerable");
        }

        private static string Escape(string text)
        {
            return text.Replace("\"", "\\\"").Replace("\n", " ");
        }
    }

    #region Models

    internal sealed class ValidatorOutput
    {
        public string FileName { get; set; } = "";
        public string Content { get; set; } = "";
    }

    internal sealed class PropertyValidationRule
    {
        public string PropertyName { get; set; } = "";
        public string PropertyType { get; set; } = "";
        public bool IsNullable { get; set; }
        public bool IsString { get; set; }
        public bool IsCollection { get; set; }
        public List<ValidationCheck> Checks { get; set; } = new List<ValidationCheck>();
    }

    internal sealed class ValidationCheck
    {
        public CheckKind Kind { get; set; }
        public string Message { get; set; } = "";
        public int IntArg { get; set; }
        public int IntArg2 { get; set; }
        public string? StringArg { get; set; }
        public string? StringArg2 { get; set; }
        public bool AllowEmptyStrings { get; set; }
    }

    internal enum CheckKind
    {
        Required,
        MaxLength,
        MinLength,
        StringLength,
        Range,
        Regex,
        Email,
        Url,
        Phone,
        Compare,
        CreditCard,
        EnumValid
    }

    #endregion
}
