using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoCode.Engine.CodeBuilder
{
    /// <summary>
    /// Fluent 代码写入器 - 替代 StringBuilder 的核心代码构建基础设施。
    /// 支持 using 自动收集、file-scoped namespace、缩进管理、region 分组。
    /// </summary>
    public sealed class CodeWriter
    {
        private readonly StringBuilder _sb = new StringBuilder();
        private readonly HashSet<string> _usings = new HashSet<string>(StringComparer.Ordinal);
        private readonly List<string> _staticUsings = new List<string>();
        private int _indentLevel;
        private string _namespace = "";
        private bool _fileScopedNamespace = true;
        private bool _nullableEnable = true;
        private string _indentString = "    ";

        /// <summary>
        /// 获取或设置缩进字符串（默认4空格）
        /// </summary>
        public CodeWriter IndentWith(string indent)
        {
            _indentString = indent;
            return this;
        }

        /// <summary>
        /// 添加 using 指令
        /// </summary>
        public CodeWriter Using(params string[] namespaces)
        {
            foreach (var ns in namespaces)
            {
                if (!string.IsNullOrWhiteSpace(ns))
                    _usings.Add(ns);
            }
            return this;
        }

        /// <summary>
        /// 添加 using static 指令
        /// </summary>
        public CodeWriter UsingStatic(string fullTypeName)
        {
            _staticUsings.Add(fullTypeName);
            return this;
        }

        /// <summary>
        /// 设置命名空间（默认 file-scoped）
        /// </summary>
        public CodeWriter Namespace(string ns, bool fileScoped = true)
        {
            _namespace = ns;
            _fileScopedNamespace = fileScoped;
            return this;
        }

        /// <summary>
        /// 设置 file-scoped namespace（C# 10+）
        /// </summary>
        public CodeWriter FileScopedNamespace(string ns)
        {
            return Namespace(ns, true);
        }

        /// <summary>
        /// 设置是否启用 #nullable enable
        /// </summary>
        public CodeWriter Nullable(bool enable = true)
        {
            _nullableEnable = enable;
            return this;
        }

        /// <summary>
        /// 写入自动生成的文件头标记
        /// </summary>
        public CodeWriter AutoGeneratedHeader()
        {
            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("// This code was generated by AutoCode Engine.");
            _sb.AppendLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
            _sb.AppendLine();
            return this;
        }

        /// <summary>
        /// 写入原始行（带当前缩进）
        /// </summary>
        public CodeWriter Line(string text = "")
        {
            if (string.IsNullOrEmpty(text))
                _sb.AppendLine();
            else
                _sb.AppendLine(GetIndent() + text);
            return this;
        }

        /// <summary>
        /// 写入原始文本（不带缩进，不带换行）
        /// </summary>
        public CodeWriter Raw(string text)
        {
            _sb.Append(text);
            return this;
        }

        /// <summary>
        /// 写入空行
        /// </summary>
        public CodeWriter BlankLine()
        {
            _sb.AppendLine();
            return this;
        }

        /// <summary>
        /// 增加缩进
        /// </summary>
        public CodeWriter Indent()
        {
            _indentLevel++;
            return this;
        }

        /// <summary>
        /// 减少缩进
        /// </summary>
        public CodeWriter Outdent()
        {
            if (_indentLevel > 0) _indentLevel--;
            return this;
        }

        /// <summary>
        /// 写入开大括号并增加缩进
        /// </summary>
        public CodeWriter OpenBrace()
        {
            Line("{");
            _indentLevel++;
            return this;
        }

        /// <summary>
        /// 减少缩进并写入闭大括号
        /// </summary>
        public CodeWriter CloseBrace(string suffix = "")
        {
            if (_indentLevel > 0) _indentLevel--;
            Line("}" + suffix);
            return this;
        }

        /// <summary>
        /// 写入 #region
        /// </summary>
        public CodeWriter Region(string name)
        {
            Line($"#region {name}");
            BlankLine();
            return this;
        }

        /// <summary>
        /// 写入 #endregion
        /// </summary>
        public CodeWriter EndRegion()
        {
            BlankLine();
            Line("#endregion");
            return this;
        }

        /// <summary>
        /// 写入 XML 文档注释
        /// </summary>
        public CodeWriter XmlDoc(string summary, params string[] remarks)
        {
            Line("/// <summary>");
            foreach (var line in SplitLines(summary))
                Line($"/// {line}");
            Line("/// </summary>");
            if (remarks.Length > 0)
            {
                Line("/// <remarks>");
                foreach (var r in remarks)
                    Line($"/// {r}");
                Line("/// </remarks>");
            }
            return this;
        }

        /// <summary>
        /// 写入 XML param 注释
        /// </summary>
        public CodeWriter XmlParam(string name, string description)
        {
            Line($"/// <param name=\"{name}\">{description}</param>");
            return this;
        }

        /// <summary>
        /// 写入 XML returns 注释
        /// </summary>
        public CodeWriter XmlReturns(string description)
        {
            Line($"/// <returns>{description}</returns>");
            return this;
        }

        /// <summary>
        /// 写入特性标注
        /// </summary>
        public CodeWriter Attribute(string attributeCode)
        {
            Line($"[{attributeCode}]");
            return this;
        }

        /// <summary>
        /// 使用 ClassBuilder 构建一个类
        /// </summary>
        public CodeWriter Class(string name, Action<ClassBuilder> configure)
        {
            var builder = new ClassBuilder(name, ClassKind.Class);
            configure(builder);
            AppendTypeBuilder(builder);
            return this;
        }

        /// <summary>
        /// 使用 ClassBuilder 构建一个接口
        /// </summary>
        public CodeWriter Interface(string name, Action<ClassBuilder> configure)
        {
            var builder = new ClassBuilder(name, ClassKind.Interface);
            configure(builder);
            AppendTypeBuilder(builder);
            return this;
        }

        /// <summary>
        /// 使用 ClassBuilder 构建一个结构体
        /// </summary>
        public CodeWriter Struct(string name, Action<ClassBuilder> configure)
        {
            var builder = new ClassBuilder(name, ClassKind.Struct);
            configure(builder);
            AppendTypeBuilder(builder);
            return this;
        }

        /// <summary>
        /// 使用 ClassBuilder 构建一个 record
        /// </summary>
        public CodeWriter Record(string name, Action<ClassBuilder> configure)
        {
            var builder = new ClassBuilder(name, ClassKind.Record);
            configure(builder);
            AppendTypeBuilder(builder);
            return this;
        }

        /// <summary>
        /// 构建最终源代码字符串（含 using + namespace 包装）
        /// </summary>
        public string Build()
        {
            var result = new StringBuilder();

            // auto-generated header 已经在 _sb 中（如果调用了的话）
            // 先输出 header 部分
            var bodyContent = _sb.ToString();

            // 写入 usings
            foreach (var u in _usings.OrderBy(x => x, UsingComparer.Instance))
                result.AppendLine($"using {u};");
            foreach (var su in _staticUsings)
                result.AppendLine($"using static {su};");

            if (_usings.Count > 0 || _staticUsings.Count > 0)
                result.AppendLine();

            // nullable
            if (_nullableEnable)
            {
                result.AppendLine("#nullable enable");
                result.AppendLine();
            }

            // namespace + body
            if (!string.IsNullOrEmpty(_namespace))
            {
                if (_fileScopedNamespace)
                {
                    result.AppendLine($"namespace {_namespace};");
                    result.AppendLine();
                    result.Append(bodyContent);
                }
                else
                {
                    result.AppendLine($"namespace {_namespace}");
                    result.AppendLine("{");
                    // 对 body 增加一级缩进
                    var indentedBody = IndentBlock(bodyContent);
                    result.Append(indentedBody);
                    result.AppendLine("}");
                }
            }
            else
            {
                result.Append(bodyContent);
            }

            return result.ToString();
        }

        /// <summary>
        /// 获取当前缩进字符串
        /// </summary>
        internal string GetIndent()
        {
            if (_indentLevel <= 0) return "";
            return string.Concat(Enumerable.Repeat(_indentString, _indentLevel));
        }

        /// <summary>
        /// 将 TypeBuilder 的内容追加到当前 writer
        /// </summary>
        internal void AppendTypeBuilder(ClassBuilder builder)
        {
            // 收集 builder 中的 usings
            foreach (var u in builder.Usings)
                _usings.Add(u);

            var content = builder.Build(this);
            _sb.Append(content);
            _sb.AppendLine();
        }

        private static string IndentBlock(string block)
        {
            var lines = block.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
            var sb = new StringBuilder();
            foreach (var line in lines)
            {
                if (string.IsNullOrWhiteSpace(line))
                    sb.AppendLine();
                else
                    sb.AppendLine("    " + line);
            }
            return sb.ToString();
        }

        private static IEnumerable<string> SplitLines(string text)
        {
            return text.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
        }

        /// <summary>
        /// using 排序比较器：System 优先
        /// </summary>
        private sealed class UsingComparer : IComparer<string>
        {
            public static readonly UsingComparer Instance = new UsingComparer();

            public int Compare(string? x, string? y)
            {
                if (x == null && y == null) return 0;
                if (x == null) return -1;
                if (y == null) return 1;

                var xSys = x.StartsWith("System", StringComparison.Ordinal);
                var ySys = y.StartsWith("System", StringComparison.Ordinal);

                if (xSys && !ySys) return -1;
                if (!xSys && ySys) return 1;
                return string.Compare(x, y, StringComparison.Ordinal);
            }
        }
    }
}
