using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoCode.WebApi
{
    /// <summary>
    /// AutoController 生成器 - 从 Service 类自动生成 API Controller
    /// </summary>
    [Generator]
    public class ControllerGenerator : IIncrementalGenerator
    {
        private const string AutoControllerAttributeFullName = "AutoCode.Model.AutoControllerAttribute";

        // HTTP 方法推断规则
        private static readonly Dictionary<string, (string HttpMethod, string Route)> HttpMethodPrefixes =
            new Dictionary<string, (string, string)>
            {
                ["GetAll"] = ("HttpGet", ""),
                ["Get"] = ("HttpGet", "{id}"),
                ["Find"] = ("HttpGet", "{id}"),
                ["Query"] = ("HttpGet", ""),
                ["List"] = ("HttpGet", ""),
                ["Create"] = ("HttpPost", ""),
                ["Add"] = ("HttpPost", ""),
                ["Insert"] = ("HttpPost", ""),
                ["Post"] = ("HttpPost", ""),
                ["Update"] = ("HttpPut", "{id}"),
                ["Modify"] = ("HttpPut", "{id}"),
                ["Put"] = ("HttpPut", "{id}"),
                ["Delete"] = ("HttpDelete", "{id}"),
                ["Remove"] = ("HttpDelete", "{id}"),
            };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var controllerSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoController" || name == "AutoControllerAttribute";
                        }),
                    transform: (ctx, _) => GenerateController(ctx))
                .Where(s => s != null)!;

            context.RegisterSourceOutput(controllerSources, (spc, source) =>
            {
                spc.AddSource(source!.FileName, SourceText.From(source.SourceText, Encoding.UTF8));
            });
        }

        private static GeneratedSource? GenerateController(GeneratorSyntaxContext ctx)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            // 查找 [AutoController] 特性
            var controllerAttr = classSymbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == AutoControllerAttributeFullName
                || a.AttributeClass?.Name == "AutoControllerAttribute");

            if (controllerAttr == null)
                return null;

            // 获取路由前缀
            var routePrefix = controllerAttr.NamedArguments
                .FirstOrDefault(a => a.Key == "RoutePrefix").Value.Value as string ?? "";

            var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "";
            var serviceClassName = classSymbol.Name;
            var controllerClassName = $"{serviceClassName}Controller";

            // 获取服务接口（用于 DI 注入）
            var serviceInterface = classSymbol.Interfaces
                .FirstOrDefault(i => i.Name != "IScoped" && i.Name != "ISingleton"
                    && i.Name != "ITransient" && i.Name != "IDependencyBase");

            var serviceTypeName = serviceInterface?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                ?? classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // 获取公共方法
            var methods = classSymbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public)
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

            sb.AppendLine($"{indent}[ApiController]");
            sb.AppendLine($"{indent}[Produces(\"application/json\")]");
            if (!string.IsNullOrEmpty(routePrefix))
                sb.AppendLine($"{indent}[Route(\"{routePrefix}\")]");
            else
                sb.AppendLine($"{indent}[Route(\"api/[controller]\")]");
            sb.AppendLine($"{indent}public class {controllerClassName} : ControllerBase");
            sb.AppendLine($"{indent}{{");

            // DI 字段和构造函数
            var fieldName = "_service";
            sb.AppendLine($"{indent}    private readonly {serviceTypeName} {fieldName};");
            sb.AppendLine();
            sb.AppendLine($"{indent}    public {controllerClassName}({serviceTypeName} service)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        {fieldName} = service;");
            sb.AppendLine($"{indent}    }}");

            // 生成 Action 方法
            foreach (var method in methods)
            {
                var (httpMethod, route) = InferHttpMethod(method.Name);
                var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var isVoid = method.ReturnType.SpecialType == SpecialType.System_Void;

                sb.AppendLine();

                // HTTP 方法特性
                if (!string.IsNullOrEmpty(route))
                    sb.AppendLine($"{indent}    [{httpMethod}(\"{route}\")]");
                else
                    sb.AppendLine($"{indent}    [{httpMethod}]");

                // Swagger 响应类型注解
                if (isVoid)
                {
                    sb.AppendLine($"{indent}    [ProducesResponseType(200)]");
                    sb.AppendLine($"{indent}    [ProducesResponseType(400)]");
                }
                else
                {
                    sb.AppendLine($"{indent}    [ProducesResponseType(typeof({returnType}), 200)]");
                    sb.AppendLine($"{indent}    [ProducesResponseType(400)]");
                }

                // 方法签名
                var parameters = method.Parameters
                    .Select(p =>
                    {
                        var paramType = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        var fromBody = IsComplexType(p.Type) ? "[FromBody] " : "";
                        return $"{fromBody}{paramType} {p.Name}";
                    });
                var paramList = string.Join(", ", parameters);

                if (isVoid)
                {
                    sb.AppendLine($"{indent}    public IActionResult {method.Name}({paramList})");
                    sb.AppendLine($"{indent}    {{");
                    var args = string.Join(", ", method.Parameters.Select(p => p.Name));
                    sb.AppendLine($"{indent}        {fieldName}.{method.Name}({args});");
                    sb.AppendLine($"{indent}        return Ok();");
                    sb.AppendLine($"{indent}    }}");
                }
                else
                {
                    sb.AppendLine($"{indent}    public ActionResult<{returnType}> {method.Name}({paramList})");
                    sb.AppendLine($"{indent}    {{");
                    var args = string.Join(", ", method.Parameters.Select(p => p.Name));
                    sb.AppendLine($"{indent}        var result = {fieldName}.{method.Name}({args});");
                    sb.AppendLine($"{indent}        return Ok(result);");
                    sb.AppendLine($"{indent}    }}");
                }
            }

            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
                sb.AppendLine("}");

            return new GeneratedSource
            {
                FileName = $"{controllerClassName}.g.cs",
                SourceText = sb.ToString()
            };
        }

        private static (string HttpMethod, string Route) InferHttpMethod(string methodName)
        {
            // 先尝试精确匹配（如 GetAll, Update, Delete）
            if (HttpMethodPrefixes.TryGetValue(methodName, out var exactMatch))
                return exactMatch;

            // 再尝试前缀匹配（如 GetById, CreateOrder）
            foreach (var kvp in HttpMethodPrefixes)
            {
                var prefix = kvp.Key;
                var mapping = kvp.Value;
                if (methodName.StartsWith(prefix) && methodName.Length > prefix.Length
                    && char.IsUpper(methodName[prefix.Length]))
                {
                    return mapping;
                }
            }

            // 默认 POST
            return ("HttpPost", methodName.ToLowerInvariant());
        }

        private static bool IsComplexType(ITypeSymbol type)
        {
            return type is INamedTypeSymbol namedType
                && !namedType.IsValueType
                && namedType.SpecialType == SpecialType.None
                && namedType.Name != "String";
        }
    }

    internal sealed class GeneratedSource
    {
        public string FileName { get; set; } = "";
        public string SourceText { get; set; } = "";
    }
}
