using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoCode.Crud
{
    /// <summary>
    /// AutoCrud 生成器 - 一键生成 CRUD Service + Interface + Controller
    /// </summary>
    [Generator]
    public class CrudGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var crudSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoCrud" || name == "AutoCrudAttribute";
                        }),
                    transform: (ctx, _) => GenerateCrud(ctx))
                .Where(s => s != null)!
                .SelectMany((sources, _) => sources);

            context.RegisterSourceOutput(crudSources, (spc, source) =>
            {
                spc.AddSource(source.FileName, SourceText.From(source.SourceText, Encoding.UTF8));
            });
        }

        private static List<GeneratedSource> GenerateCrud(GeneratorSyntaxContext ctx)
        {
            var result = new List<GeneratedSource>();

            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return result;

            var entitySymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (entitySymbol == null)
                return result;

            var namespaceName = entitySymbol.ContainingNamespace?.ToDisplayString() ?? "";
            var entityName = entitySymbol.Name;
            var entityFullName = entitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // 获取主键属性
            var keyProp = entitySymbol.GetMembers().OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == "Id");
            var keyType = keyProp?.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "int";

            // 获取所有公共属性
            var properties = entitySymbol.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                .Where(p => !p.IsStatic && !p.IsIndexer)
                .ToList();

            // 1. 生成 IService 接口
            result.Add(new GeneratedSource
            {
                FileName = $"I{entityName}Service.g.cs",
                SourceText = GenerateIService(namespaceName, entityName, entityFullName, keyType)
            });

            // 2. 生成 Service 实现（内存存储）
            result.Add(new GeneratedSource
            {
                FileName = $"{entityName}Service.g.cs",
                SourceText = GenerateService(namespaceName, entityName, entityFullName, keyType, properties)
            });

            // 3. 生成 Controller
            result.Add(new GeneratedSource
            {
                FileName = $"{entityName}sController.g.cs",
                SourceText = GenerateController(namespaceName, entityName, entityFullName, keyType)
            });

            return result;
        }

        private static string GenerateIService(string ns, string entity, string entityFull, string keyType)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(ns)) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }
            var i = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.AppendLine($"{i}/// <summary>");
            sb.AppendLine($"{i}/// {entity} CRUD 服务接口（由 AutoCode.Crud 自动生成）");
            sb.AppendLine($"{i}/// </summary>");
            sb.AppendLine($"{i}public interface I{entity}Service");
            sb.AppendLine($"{i}{{");
            sb.AppendLine($"{i}    List<{entityFull}> GetAll();");
            sb.AppendLine($"{i}    {entityFull}? GetById({keyType} id);");
            sb.AppendLine($"{i}    {entityFull} Create({entityFull} entity);");
            sb.AppendLine($"{i}    {entityFull}? Update({keyType} id, {entityFull} entity);");
            sb.AppendLine($"{i}    bool Delete({keyType} id);");
            sb.AppendLine($"{i}}}");

            if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateService(string ns, string entity, string entityFull, string keyType,
            List<IPropertySymbol> properties)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(ns)) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }
            var i = string.IsNullOrEmpty(ns) ? "" : "    ";

            sb.AppendLine($"{i}/// <summary>");
            sb.AppendLine($"{i}/// {entity} CRUD 服务内存实现（由 AutoCode.Crud 自动生成，可替换为 EF Core）");
            sb.AppendLine($"{i}/// </summary>");
            sb.AppendLine($"{i}public class {entity}Service : I{entity}Service");
            sb.AppendLine($"{i}{{");
            sb.AppendLine($"{i}    private readonly List<{entityFull}> _store = new();");
            sb.AppendLine($"{i}    private {keyType} _nextId = default;");
            sb.AppendLine();

            // GetAll
            sb.AppendLine($"{i}    public List<{entityFull}> GetAll() => _store.ToList();");
            sb.AppendLine();

            // GetById
            sb.AppendLine($"{i}    public {entityFull}? GetById({keyType} id)");
            sb.AppendLine($"{i}        => _store.FirstOrDefault(e => e.Id.Equals(id));");
            sb.AppendLine();

            // Create
            sb.AppendLine($"{i}    public {entityFull} Create({entityFull} entity)");
            sb.AppendLine($"{i}    {{");
            sb.AppendLine($"{i}        _store.Add(entity);");
            sb.AppendLine($"{i}        return entity;");
            sb.AppendLine($"{i}    }}");
            sb.AppendLine();

            // Update
            sb.AppendLine($"{i}    public {entityFull}? Update({keyType} id, {entityFull} entity)");
            sb.AppendLine($"{i}    {{");
            sb.AppendLine($"{i}        var existing = _store.FirstOrDefault(e => e.Id.Equals(id));");
            sb.AppendLine($"{i}        if (existing == null) return null;");
            sb.AppendLine($"{i}        var index = _store.IndexOf(existing);");
            sb.AppendLine($"{i}        _store[index] = entity;");
            sb.AppendLine($"{i}        return entity;");
            sb.AppendLine($"{i}    }}");
            sb.AppendLine();

            // Delete
            sb.AppendLine($"{i}    public bool Delete({keyType} id)");
            sb.AppendLine($"{i}    {{");
            sb.AppendLine($"{i}        var existing = _store.FirstOrDefault(e => e.Id.Equals(id));");
            sb.AppendLine($"{i}        if (existing == null) return false;");
            sb.AppendLine($"{i}        return _store.Remove(existing);");
            sb.AppendLine($"{i}    }}");

            sb.AppendLine($"{i}}}");
            if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateController(string ns, string entity, string entityFull, string keyType)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(ns)) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }
            var i = string.IsNullOrEmpty(ns) ? "" : "    ";

            var route = $"api/{entity.ToLowerInvariant()}s";

            sb.AppendLine($"{i}[ApiController]");
            sb.AppendLine($"{i}[Route(\"{route}\")]");
            sb.AppendLine($"{i}[Produces(\"application/json\")]");
            sb.AppendLine($"{i}public class {entity}sController : ControllerBase");
            sb.AppendLine($"{i}{{");
            sb.AppendLine($"{i}    private readonly I{entity}Service _service;");
            sb.AppendLine();
            sb.AppendLine($"{i}    public {entity}sController(I{entity}Service service) => _service = service;");
            sb.AppendLine();

            // GET all
            sb.AppendLine($"{i}    [HttpGet]");
            sb.AppendLine($"{i}    [ProducesResponseType(typeof(List<{entityFull}>), 200)]");
            sb.AppendLine($"{i}    public ActionResult<List<{entityFull}>> GetAll() => Ok(_service.GetAll());");
            sb.AppendLine();

            // GET by id
            sb.AppendLine($"{i}    [HttpGet(\"{{id}}\")]");
            sb.AppendLine($"{i}    [ProducesResponseType(typeof({entityFull}), 200)]");
            sb.AppendLine($"{i}    [ProducesResponseType(404)]");
            sb.AppendLine($"{i}    public ActionResult<{entityFull}> GetById({keyType} id)");
            sb.AppendLine($"{i}    {{");
            sb.AppendLine($"{i}        var result = _service.GetById(id);");
            sb.AppendLine($"{i}        return result == null ? NotFound() : Ok(result);");
            sb.AppendLine($"{i}    }}");
            sb.AppendLine();

            // POST
            sb.AppendLine($"{i}    [HttpPost]");
            sb.AppendLine($"{i}    [ProducesResponseType(typeof({entityFull}), 201)]");
            sb.AppendLine($"{i}    public ActionResult<{entityFull}> Create([FromBody] {entityFull} entity)");
            sb.AppendLine($"{i}    {{");
            sb.AppendLine($"{i}        var result = _service.Create(entity);");
            sb.AppendLine($"{i}        return CreatedAtAction(nameof(GetById), new {{ id = result.Id }}, result);");
            sb.AppendLine($"{i}    }}");
            sb.AppendLine();

            // PUT
            sb.AppendLine($"{i}    [HttpPut(\"{{id}}\")]");
            sb.AppendLine($"{i}    [ProducesResponseType(typeof({entityFull}), 200)]");
            sb.AppendLine($"{i}    [ProducesResponseType(404)]");
            sb.AppendLine($"{i}    public ActionResult<{entityFull}> Update({keyType} id, [FromBody] {entityFull} entity)");
            sb.AppendLine($"{i}    {{");
            sb.AppendLine($"{i}        var result = _service.Update(id, entity);");
            sb.AppendLine($"{i}        return result == null ? NotFound() : Ok(result);");
            sb.AppendLine($"{i}    }}");
            sb.AppendLine();

            // DELETE
            sb.AppendLine($"{i}    [HttpDelete(\"{{id}}\")]");
            sb.AppendLine($"{i}    [ProducesResponseType(204)]");
            sb.AppendLine($"{i}    [ProducesResponseType(404)]");
            sb.AppendLine($"{i}    public IActionResult Delete({keyType} id)");
            sb.AppendLine($"{i}    {{");
            sb.AppendLine($"{i}        return _service.Delete(id) ? NoContent() : NotFound();");
            sb.AppendLine($"{i}    }}");

            sb.AppendLine($"{i}}}");
            if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}");
            return sb.ToString();
        }
    }

    internal sealed class GeneratedSource
    {
        public string FileName { get; set; } = "";
        public string SourceText { get; set; } = "";
    }
}
