using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoCode.DependencyInjection
{
    /// <summary>
    /// 编译时依赖注入注册生成器
    /// 扫描实现 IScoped/ISingleton/ITransient 的类，生成静态 DI 注册代码
    /// 替代运行时反射扫描，兼容 NativeAOT
    /// </summary>
    [Generator]
    public class DependencyInjectionGenerator : IIncrementalGenerator
    {
        private static readonly HashSet<string> LifetimeInterfaceNames = new HashSet<string>
        {
            "IScoped", "ISingleton", "ITransient", "IDependencyBase"
        };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var registrations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => ExtractRegistration(ctx))
                .Where(r => r != null)!
                .Collect();

            context.RegisterSourceOutput(registrations, (spc, items) =>
            {
                if (items.Length == 0) return;

                var source = GenerateSource(items!);
                spc.AddSource("AutoDependencyInjection.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }

        /// <summary>
        /// 从类中提取 DI 注册信息
        /// </summary>
        private static ServiceRegistration? ExtractRegistration(GeneratorSyntaxContext ctx)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            // 跳过抽象类和静态类
            if (classSymbol.IsAbstract || classSymbol.IsStatic)
                return null;

            // 查找生命周期接口
            string? lifetime = null;
            foreach (var iface in classSymbol.AllInterfaces)
            {
                var name = iface.Name;
                if (name == "IScoped") lifetime = "Scoped";
                else if (name == "ISingleton") lifetime = "Singleton";
                else if (name == "ITransient") lifetime = "Transient";
            }

            if (lifetime == null)
                return null;

            // 获取服务接口（排除生命周期接口和 IDependencyBase）
            var serviceInterfaces = classSymbol.Interfaces
                .Where(i => !LifetimeInterfaceNames.Contains(i.Name))
                .Select(i => i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .ToList();

            var implementationType = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            return new ServiceRegistration(implementationType, serviceInterfaces, lifetime);
        }

        /// <summary>
        /// 生成 DI 注册源代码
        /// </summary>
        private static string GenerateSource(System.Collections.Immutable.ImmutableArray<ServiceRegistration> registrations)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
            sb.AppendLine();
            sb.AppendLine("namespace AutoCode.DependencyInjection");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 编译时依赖注入注册（由 AutoCode.DependencyInjection 生成器自动生成）");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class AutoDependencyInjection");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 注册所有标记了 IScoped/ISingleton/ITransient 的服务");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static IServiceCollection AddAutoDI(this IServiceCollection services)");
            sb.AppendLine("        {");

            foreach (var reg in registrations)
            {
                if (reg.ServiceInterfaces.Count > 0)
                {
                    foreach (var serviceInterface in reg.ServiceInterfaces)
                    {
                        sb.AppendLine($"            services.TryAdd{reg.Lifetime}<{serviceInterface}, {reg.ImplementationType}>();");
                    }
                }
                else
                {
                    // 无服务接口时注册自身
                    sb.AppendLine($"            services.TryAdd{reg.Lifetime}<{reg.ImplementationType}, {reg.ImplementationType}>();");
                }
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }

    /// <summary>
    /// 服务注册信息
    /// </summary>
    internal sealed class ServiceRegistration
    {
        public string ImplementationType { get; }
        public List<string> ServiceInterfaces { get; }
        public string Lifetime { get; }

        public ServiceRegistration(string implementationType, List<string> serviceInterfaces, string lifetime)
        {
            ImplementationType = implementationType;
            ServiceInterfaces = serviceInterfaces;
            Lifetime = lifetime;
        }
    }
}
