using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using AutoCode.Engine.CodeBuilder;

namespace AutoCode.Plugins.Testing
{
    /// <summary>
    /// 测试生成器 v2 - 生成有意义的单元测试：
    /// 自动 Mock 构造函数依赖、边界值测试、异常路径、Arrange-Act-Assert 模式。
    /// </summary>
    [Generator]
    public class TestGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var testSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoTest" || name == "AutoTestAttribute";
                        }),
                    transform: static (ctx, ct) => ExtractTestInfo(ctx, ct))
                .Where(static s => s != null);

            context.RegisterSourceOutput(testSources, static (spc, info) =>
            {
                var output = GenerateTests(info!);
                if (output != null)
                    spc.AddSource(output.FileName, SourceText.From(output.Content, Encoding.UTF8));
            });
        }

        private static TestInfo? ExtractTestInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            // 获取构造函数依赖
            var ctor = classSymbol.InstanceConstructors
                .OrderByDescending(c => c.Parameters.Length)
                .FirstOrDefault();

            var dependencies = ctor?.Parameters
                .Select(p => new DepInfo
                {
                    Name = p.Name,
                    Type = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    ShortType = p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                    IsInterface = p.Type.TypeKind == TypeKind.Interface
                })
                .ToList() ?? new List<DepInfo>();

            // 获取公共方法
            var methods = classSymbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public)
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .Select(m => new MethodTestInfo
                {
                    Name = m.Name,
                    IsAsync = IsAsync(m.ReturnType),
                    IsVoid = m.ReturnType.SpecialType == SpecialType.System_Void
                        || m.ReturnType.ToDisplayString() == "System.Threading.Tasks.Task",
                    ReturnTypeName = GetReturnName(m.ReturnType),
                    Parameters = m.Parameters.Select(p => new ParamTestInfo
                    {
                        Name = p.Name,
                        Type = p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                        SpecialType = p.Type.SpecialType
                    }).ToList()
                })
                .ToList();

            if (methods.Count == 0)
                return null;

            return new TestInfo
            {
                ClassName = classSymbol.Name,
                Namespace = classSymbol.ContainingNamespace?.ToDisplayString() ?? "",
                Dependencies = dependencies,
                Methods = methods
            };
        }

        private static TestOutput? GenerateTests(TestInfo info)
        {
            var testClassName = $"{info.ClassName}Tests";
            var w = new CodeWriter();
            w.AutoGeneratedHeader();
            w.Using("System", "System.Threading.Tasks", "Xunit", "Moq");
            w.FileScopedNamespace(info.Namespace);

            w.Class(testClassName, c =>
            {
                c.Public();
                c.Doc($"{info.ClassName} 的自动生成测试（由 AutoCode Testing 插件生成）");

                // Mock 字段
                foreach (var dep in info.Dependencies.Where(d => d.IsInterface))
                {
                    var fieldName = $"_mock{dep.ShortType.TrimStart('I')}";
                    c.Field(fieldName, f => f.Private().ReadOnly().Type($"Mock<{dep.ShortType}>"));
                }

                c.Field("_sut", f => f.Private().ReadOnly().Type(info.ClassName));

                // 构造函数 - 初始化 Mock + SUT
                c.Constructor(ctor =>
                {
                    foreach (var dep in info.Dependencies.Where(d => d.IsInterface))
                    {
                        var fieldName = $"_mock{dep.ShortType.TrimStart('I')}";
                        ctor.Body($"{fieldName} = new Mock<{dep.ShortType}>();");
                    }

                    var ctorArgs = string.Join(", ", info.Dependencies.Select(d =>
                        d.IsInterface ? $"_mock{d.ShortType.TrimStart('I')}.Object" : GetDefaultNew(d.ShortType)));
                    ctor.Body($"_sut = new {info.ClassName}({ctorArgs});");
                });

                // 为每个方法生成测试
                foreach (var method in info.Methods)
                {
                    GenerateMethodTests(c, method, info);
                }
            });

            return new TestOutput
            {
                FileName = $"{testClassName}.g.cs",
                Content = w.Build()
            };
        }

        private static void GenerateMethodTests(ClassBuilder c, MethodTestInfo method, TestInfo info)
        {
            // 1. 正常路径测试
            c.Method($"{method.Name}_Should_Succeed", m =>
            {
                m.Public();
                if (method.IsAsync) m.Async();
                m.Attribute("Fact");
                m.Attribute($"Trait(\"Category\", \"{info.ClassName}\")");

                if (method.IsAsync)
                    m.Returns("Task");

                m.Body(b =>
                {
                    b.Comment("Arrange");
                    foreach (var param in method.Parameters)
                    {
                        b.Var(param.Name, GetTestValue(param));
                    }

                    b.Comment("Act");
                    var args = string.Join(", ", method.Parameters.Select(p => p.Name));
                    if (method.IsAsync)
                    {
                        if (method.IsVoid)
                            b.Line($"await _sut.{method.Name}({args});");
                        else
                            b.Var("result", $"await _sut.{method.Name}({args})");
                    }
                    else
                    {
                        if (!method.IsVoid)
                            b.Var("result", $"_sut.{method.Name}({args})");
                        else
                            b.Line($"_sut.{method.Name}({args});");
                    }

                    b.Comment("Assert");
                    if (!method.IsVoid)
                    {
                        b.Line("Assert.NotNull(result);");
                    }
                    else
                    {
                        b.Line("// Method completed without exception");
                    }
                });
            });

            // 2. 空参数异常测试（如果有引用类型参数）
            var refParams = method.Parameters.Where(p =>
                p.SpecialType == SpecialType.System_String || p.SpecialType == SpecialType.None).ToList();

            if (refParams.Count > 0)
            {
                c.Method($"{method.Name}_NullArg_Should_Throw", m =>
                {
                    m.Public();
                    if (method.IsAsync) m.Async();
                    m.Attribute("Fact");

                    if (method.IsAsync)
                        m.Returns("Task");

                    m.Body(b =>
                    {
                        b.Comment("Arrange");
                        foreach (var param in method.Parameters)
                        {
                            if (refParams.Contains(param))
                                b.Var(param.Name, "null!");
                            else
                                b.Var(param.Name, GetTestValue(param));
                        }

                        b.Comment("Act & Assert");
                        var args = string.Join(", ", method.Parameters.Select(p => p.Name));
                        if (method.IsAsync)
                            b.Line($"await Assert.ThrowsAnyAsync<Exception>(() => _sut.{method.Name}({args}));");
                        else
                            b.Line($"Assert.ThrowsAny<Exception>(() => _sut.{method.Name}({args}));");
                    });
                });
            }
        }

        private static string GetTestValue(ParamTestInfo param)
        {
            switch (param.SpecialType)
            {
                case SpecialType.System_Int32: return "1";
                case SpecialType.System_Int64: return "1L";
                case SpecialType.System_String: return "\"test\"";
                case SpecialType.System_Boolean: return "true";
                case SpecialType.System_Double: return "1.0";
                case SpecialType.System_Single: return "1.0f";
                case SpecialType.System_Decimal: return "1m";
                case SpecialType.System_DateTime: return "DateTime.UtcNow";
                default:
                    if (param.Type.EndsWith("?"))
                        return "null";
                    return $"new {param.Type}()";
            }
        }

        private static string GetDefaultNew(string type)
        {
            if (type.StartsWith("ILogger"))
                return "new Mock<Microsoft.Extensions.Logging.ILogger>().Object";
            return $"new {type}()";
        }

        private static bool IsAsync(ITypeSymbol type)
        {
            if (type is not INamedTypeSymbol named) return false;
            var full = named.OriginalDefinition.ToDisplayString();
            return full.StartsWith("System.Threading.Tasks.Task")
                || full.StartsWith("System.Threading.Tasks.ValueTask");
        }

        private static string GetReturnName(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol named && named.IsGenericType)
                return named.TypeArguments.Last().Name;
            return type.Name;
        }
    }

    #region Models

    internal sealed class TestInfo
    {
        public string ClassName { get; set; } = "";
        public string Namespace { get; set; } = "";
        public List<DepInfo> Dependencies { get; set; } = new List<DepInfo>();
        public List<MethodTestInfo> Methods { get; set; } = new List<MethodTestInfo>();
    }

    internal sealed class DepInfo
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
        public string ShortType { get; set; } = "";
        public bool IsInterface { get; set; }
    }

    internal sealed class MethodTestInfo
    {
        public string Name { get; set; } = "";
        public bool IsAsync { get; set; }
        public bool IsVoid { get; set; }
        public string ReturnTypeName { get; set; } = "";
        public List<ParamTestInfo> Parameters { get; set; } = new List<ParamTestInfo>();
    }

    internal sealed class ParamTestInfo
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
        public SpecialType SpecialType { get; set; }
    }

    internal sealed class TestOutput
    {
        public string FileName { get; set; } = "";
        public string Content { get; set; } = "";
    }

    #endregion
}
