using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;

namespace AutoCode.Logging
{
    /// <summary>
    /// AutoLog 生成器 - 自动生成日志装饰器（Decorator Pattern）
    /// </summary>
    [Generator]
    public class LogDecoratorGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var logSources = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax cds &&
                        cds.AttributeLists.SelectMany(a => a.Attributes).Any(a =>
                        {
                            var name = a.Name is IdentifierNameSyntax id ? id.Identifier.Text : a.Name.ToString();
                            return name == "AutoLog" || name == "AutoLogAttribute";
                        }),
                    transform: (ctx, _) => GenerateDecorator(ctx))
                .Where(s => s != null)!;

            context.RegisterSourceOutput(logSources, (spc, source) =>
            {
                spc.AddSource(source!.FileName, SourceText.From(source.SourceText, Encoding.UTF8));
            });
        }

        private static GeneratedSource? GenerateDecorator(GeneratorSyntaxContext ctx)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDecl)
                return null;

            var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (classSymbol == null)
                return null;

            // 获取服务接口
            var serviceInterface = classSymbol.Interfaces
                .FirstOrDefault(i => i.Name != "IScoped" && i.Name != "ISingleton"
                    && i.Name != "ITransient" && i.Name != "IDependencyBase");

            if (serviceInterface == null)
                return null;

            var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString() ?? "";
            var className = classSymbol.Name;
            var interfaceName = serviceInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var decoratorName = $"Logging{className}";

            var methods = serviceInterface.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.Extensions.Logging;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Diagnostics;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// {className} 的日志装饰器（由 AutoCode.Logging 自动生成）");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public class {decoratorName} : {interfaceName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    private readonly {interfaceName} _inner;");
            sb.AppendLine($"{indent}    private readonly ILogger<{decoratorName}> _logger;");
            sb.AppendLine();
            sb.AppendLine($"{indent}    public {decoratorName}({interfaceName} inner, ILogger<{decoratorName}> logger)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        _inner = inner;");
            sb.AppendLine($"{indent}        _logger = logger;");
            sb.AppendLine($"{indent}    }}");

            foreach (var method in methods)
            {
                var isAsync = IsAsyncReturn(method.ReturnType);
                var isVoid = method.ReturnType.SpecialType == SpecialType.System_Void;
                var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                var parameters = string.Join(", ",
                    method.Parameters.Select(p =>
                        $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));
                var args = string.Join(", ", method.Parameters.Select(p => p.Name));
                var paramLog = method.Parameters.Length > 0
                    ? ", " + string.Join(", ", method.Parameters.Select(p => $"{p.Name}={{{p.Name}}}"))
                    : "";
                var paramNames = method.Parameters.Length > 0
                    ? ", " + string.Join(", ", method.Parameters.Select(p => p.Name))
                    : "";

                sb.AppendLine();

                if (isAsync)
                {
                    sb.AppendLine($"{indent}    public async {returnType} {method.Name}({parameters})");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        _logger.LogInformation(\"{method.Name} 开始{paramLog}\"{paramNames});");
                    sb.AppendLine($"{indent}        var sw = Stopwatch.StartNew();");
                    sb.AppendLine($"{indent}        try");
                    sb.AppendLine($"{indent}        {{");
                    if (isVoid || returnType.EndsWith("Task"))
                    {
                        sb.AppendLine($"{indent}            await _inner.{method.Name}({args});");
                        sb.AppendLine($"{indent}            _logger.LogInformation(\"{method.Name} 完成, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}            var result = await _inner.{method.Name}({args});");
                        sb.AppendLine($"{indent}            _logger.LogInformation(\"{method.Name} 完成, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                        sb.AppendLine($"{indent}            return result;");
                    }
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        catch (Exception ex)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            _logger.LogError(ex, \"{method.Name} 异常, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                    sb.AppendLine($"{indent}            throw;");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}    }}");
                }
                else if (isVoid)
                {
                    sb.AppendLine($"{indent}    public void {method.Name}({parameters})");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        _logger.LogInformation(\"{method.Name} 开始{paramLog}\"{paramNames});");
                    sb.AppendLine($"{indent}        var sw = Stopwatch.StartNew();");
                    sb.AppendLine($"{indent}        try");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            _inner.{method.Name}({args});");
                    sb.AppendLine($"{indent}            _logger.LogInformation(\"{method.Name} 完成, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        catch (Exception ex)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            _logger.LogError(ex, \"{method.Name} 异常, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                    sb.AppendLine($"{indent}            throw;");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}    }}");
                }
                else
                {
                    sb.AppendLine($"{indent}    public {returnType} {method.Name}({parameters})");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        _logger.LogInformation(\"{method.Name} 开始{paramLog}\"{paramNames});");
                    sb.AppendLine($"{indent}        var sw = Stopwatch.StartNew();");
                    sb.AppendLine($"{indent}        try");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            var result = _inner.{method.Name}({args});");
                    sb.AppendLine($"{indent}            _logger.LogInformation(\"{method.Name} 完成, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                    sb.AppendLine($"{indent}            return result;");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        catch (Exception ex)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            _logger.LogError(ex, \"{method.Name} 异常, 耗时 {{Elapsed}}ms\", sw.ElapsedMilliseconds);");
                    sb.AppendLine($"{indent}            throw;");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}    }}");
                }
            }

            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
                sb.AppendLine("}");

            return new GeneratedSource
            {
                FileName = $"{decoratorName}.g.cs",
                SourceText = sb.ToString()
            };
        }

        private static bool IsAsyncReturn(ITypeSymbol type)
        {
            if (type is not INamedTypeSymbol named) return false;
            var full = named.OriginalDefinition.ToDisplayString();
            return full.StartsWith("System.Threading.Tasks.Task")
                || full.StartsWith("System.Threading.Tasks.ValueTask");
        }
    }

    internal sealed class GeneratedSource
    {
        public string FileName { get; set; } = "";
        public string SourceText { get; set; } = "";
    }
}
