<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>12.0</LangVersion>
		<Nullable>enable</Nullable>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<NoWarn>RS1035;RS1036</NoWarn>
		<GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" PrivateAssets="all" />
		<PackageReference Include="DotLiquid" Version="2.2.692" GeneratePathProperty="true" PrivateAssets="all" />
	</ItemGroup>

	<Target Name="GetDependencyTargetPaths">
		<ItemGroup Condition="'$(Configuration)' == 'Debug'">
			<TargetPathWithTargetPlatformMoniker Include="$(PKGDotLiquid)\lib\netstandard2.0\DotLiquid.dll" IncludeRuntimeDependency="false" />
		</ItemGroup>
		<ItemGroup Condition="'$(Configuration)' == 'Release'">
			<TargetPathWithTargetPlatformMoniker Include="$(PKGDotLiquid)\lib\netstandard2.0\DotLiquid.dll" IncludeRuntimeDependency="false" />
		</ItemGroup>
	</Target>


</Project>
