<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>12.0</LangVersion>
		<Nullable>enable</Nullable>
		<GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
	</PropertyGroup>

	<ItemGroup>

		<PackageReference Include="Jint" Version="2.11.58" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" GeneratePathProperty="true" PrivateAssets="all" />
		<PackageReference Include="DotLiquid" Version="2.2.692" GeneratePathProperty="true" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Extend\doT.js">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="GetDependencyTargetPaths">
		<ItemGroup Condition="'$(Configuration)' == 'Debug'">
			<TargetPathWithTargetPlatformMoniker Include="$(PKGNewtonsoft_Json)\lib\netstandard2.0\Newtonsoft.Json.dll" IncludeRuntimeDependency="false" />
			<TargetPathWithTargetPlatformMoniker Include="$(PKGDotLiquid)\lib\netstandard2.0\DotLiquid.dll" IncludeRuntimeDependency="false" />
		</ItemGroup>
		<ItemGroup Condition="'$(Configuration)' == 'Release'">
			<TargetPathWithTargetPlatformMoniker Include="$(PKGNewtonsoft_Json)\lib\netstandard2.0\Newtonsoft.Json.dll" IncludeRuntimeDependency="false" />
			<TargetPathWithTargetPlatformMoniker Include="$(PKGDotLiquid)\lib\netstandard2.0\DotLiquid.dll" IncludeRuntimeDependency="false" />
		</ItemGroup>
	</Target>


</Project>
