using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using AutoCode.Engine.CodeBuilder;
using AutoCode.Engine.Config;
using AutoCode.Engine.Diagnostics;
using AutoCode.Engine.Pipeline;
using AutoCode.Engine.Plugin;

// 重新导出核心命名空间，第三方插件只需 using AutoCode.Plugin.Sdk
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("AutoCode.Plugin.Sdk.Tests")]

namespace AutoCode.Plugin.Sdk
{
    /// <summary>
    /// 插件开发辅助工具 - 简化第三方插件的创建和测试。
    /// </summary>
    public static class PluginDevTools
    {
        /// <summary>
        /// 创建用于测试的 GenerationContext（无需真实编译环境）
        /// </summary>
        public static GenerationContext CreateTestContext(
            string? sourceCode = null,
            IAutoCodeConfig? config = null)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode ?? "");
            var compilation = CSharpCompilation.Create("TestAssembly",
                new[] { syntaxTree },
                new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) });

            return new GenerationContext(
                compilation,
                config ?? new AutoCodeConfig(),
                new DiagnosticCollector());
        }

        /// <summary>
        /// 从源代码编译并提取指定类型符号（用于测试）
        /// </summary>
        public static INamedTypeSymbol? GetTypeFromSource(string sourceCode, string typeName)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
            var compilation = CSharpCompilation.Create("TestAssembly",
                new[] { syntaxTree },
                new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location)
                });

            var symbol = compilation.GetTypeByMetadataName(typeName);
            return symbol;
        }

        /// <summary>
        /// 验证生成的代码是否可以编译（用于测试）
        /// </summary>
        public static (bool Success, List<string> Errors) ValidateGeneratedCode(string generatedCode)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(generatedCode);
            var compilation = CSharpCompilation.Create("ValidationAssembly",
                new[] { syntaxTree },
                new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location)
                },
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var diagnostics = compilation.GetDiagnostics()
                .Where(d => d.Severity == DiagnosticSeverity.Error)
                .Select(d => d.ToString())
                .ToList();

            return (diagnostics.Count == 0, diagnostics);
        }

        /// <summary>
        /// 快速创建 CodeWriter 并生成代码（简化 API）
        /// </summary>
        public static string QuickGenerate(string ns, string className, Action<ClassBuilder> configure)
        {
            var writer = new CodeWriter();
            writer.AutoGeneratedHeader();
            writer.Using("System", "System.Collections.Generic");
            writer.FileScopedNamespace(ns);
            writer.Class(className, configure);
            return writer.Build();
        }
    }

    /// <summary>
    /// 插件注册辅助 - 在程序集级别标记插件以便引擎自动发现
    /// </summary>
    /// <example>
    /// <code>
    /// // 在 AssemblyInfo.cs 中：
    /// [assembly: RegisterAutoCodePlugin(typeof(MyCustomGenerator))]
    /// </code>
    /// </example>
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public sealed class RegisterAutoCodePluginAttribute : Attribute
    {
        public Type PluginType { get; }
        public RegisterAutoCodePluginAttribute(Type pluginType) => PluginType = pluginType;
    }
}
